[2023-11-09T02:05:23.334+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=export_google_data_v02/run_id=manual__2023-11-07T01:20:11.827106+00:00/task_id=3rd_task permission to 509
[2023-11-09T02:05:23.780+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=export_google_data_v02/run_id=manual__2023-11-07T01:20:11.827106+00:00/task_id=3rd_task permission to 509
[2023-11-09T02:05:24.844+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: export_google_data_v02.3rd_task manual__2023-11-07T01:20:11.827106+00:00 [queued]>
[2023-11-09T02:05:24.881+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: export_google_data_v02.3rd_task manual__2023-11-07T01:20:11.827106+00:00 [queued]>
[2023-11-09T02:05:24.884+0000] {taskinstance.py:1361} INFO - Starting attempt 6 of 6
[2023-11-09T02:05:24.929+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): 3rd_task> on 2023-11-07 01:20:11.827106+00:00
[2023-11-09T02:05:24.944+0000] {standard_task_runner.py:57} INFO - Started process 2952 to run task
[2023-11-09T02:05:24.951+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'export_google_data_v02', '3rd_task', 'manual__2023-11-07T01:20:11.827106+00:00', '--job-id', '461', '--raw', '--subdir', 'DAGS_FOLDER/export_data.py', '--cfg-path', '/tmp/tmp7mikbay2']
[2023-11-09T02:05:24.958+0000] {standard_task_runner.py:85} INFO - Job 461: Subtask 3rd_task
[2023-11-09T02:05:25.073+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=export_google_data_v02/run_id=manual__2023-11-07T01:20:11.827106+00:00/task_id=3rd_task permission to 509
[2023-11-09T02:05:25.087+0000] {task_command.py:416} INFO - Running <TaskInstance: export_google_data_v02.3rd_task manual__2023-11-07T01:20:11.827106+00:00 [running]> on host a4fee2fb2c17
[2023-11-09T02:05:25.271+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Toema' AIRFLOW_CTX_DAG_ID='export_google_data_v02' AIRFLOW_CTX_TASK_ID='3rd_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-07T01:20:11.827106+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-07T01:20:11.827106+00:00'
[2023-11-09T02:05:25.273+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-09T02:05:25.276+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/src/scripts/export_data.py']
[2023-11-09T02:05:25.297+0000] {subprocess.py:86} INFO - Output:
[2023-11-09T02:06:16.080+0000] {subprocess.py:97} INFO - Command exited with return code -9
[2023-11-09T02:06:17.069+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code -9.
[2023-11-09T02:06:17.665+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=export_google_data_v02, task_id=3rd_task, execution_date=20231107T012011, start_date=20231109T020524, end_date=20231109T020617
[2023-11-09T02:06:21.393+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 461 for task 3rd_task (Bash command failed. The command returned a non-zero exit code -9.; 2952)
[2023-11-09T02:06:23.759+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-09T02:06:23.917+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
