[2023-11-07T01:20:19.365+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=export_google_data_v02/run_id=manual__2023-11-07T01:20:11.827106+00:00/task_id=3rd_task permission to 509
[2023-11-07T01:20:19.621+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=export_google_data_v02/run_id=manual__2023-11-07T01:20:11.827106+00:00/task_id=3rd_task permission to 509
[2023-11-07T01:20:19.859+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: export_google_data_v02.3rd_task manual__2023-11-07T01:20:11.827106+00:00 [queued]>
[2023-11-07T01:20:19.895+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: export_google_data_v02.3rd_task manual__2023-11-07T01:20:11.827106+00:00 [queued]>
[2023-11-07T01:20:19.897+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-11-07T01:20:19.968+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): 3rd_task> on 2023-11-07 01:20:11.827106+00:00
[2023-11-07T01:20:19.989+0000] {standard_task_runner.py:57} INFO - Started process 8877 to run task
[2023-11-07T01:20:20.024+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'export_google_data_v02', '3rd_task', 'manual__2023-11-07T01:20:11.827106+00:00', '--job-id', '275', '--raw', '--subdir', 'DAGS_FOLDER/export_data.py', '--cfg-path', '/tmp/tmpk_fryzec']
[2023-11-07T01:20:20.053+0000] {standard_task_runner.py:85} INFO - Job 275: Subtask 3rd_task
[2023-11-07T01:20:20.299+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=export_google_data_v02/run_id=manual__2023-11-07T01:20:11.827106+00:00/task_id=3rd_task permission to 509
[2023-11-07T01:20:20.315+0000] {task_command.py:416} INFO - Running <TaskInstance: export_google_data_v02.3rd_task manual__2023-11-07T01:20:11.827106+00:00 [running]> on host c4630ce72677
[2023-11-07T01:20:20.686+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Toema' AIRFLOW_CTX_DAG_ID='export_google_data_v02' AIRFLOW_CTX_TASK_ID='3rd_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-07T01:20:11.827106+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-07T01:20:11.827106+00:00'
[2023-11-07T01:20:20.692+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-07T01:20:20.710+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/src/scripts/export_data.py']
[2023-11-07T01:20:20.745+0000] {subprocess.py:86} INFO - Output:
[2023-11-07T01:20:50.278+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-11-07T01:20:50.281+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/src/scripts/export_data.py", line 96, in <module>
[2023-11-07T01:20:50.284+0000] {subprocess.py:93} INFO -     license_utils.export_aggregated_license(path_utils.path_to('export_cc_by_license'),
[2023-11-07T01:20:50.287+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/src/scripts/../../src/pipeline/license_utils.py", line 60, in export_aggregated_license
[2023-11-07T01:20:50.289+0000] {subprocess.py:93} INFO -     with open(export_path, 'w',encoding="UTF-8", errors="ignore") as outfile:
[2023-11-07T01:20:50.292+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/opt/***/dags/data/exports/cc_by/LICENSE'
[2023-11-07T01:20:51.022+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-11-07T01:20:51.074+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-11-07T01:20:51.132+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=export_google_data_v02, task_id=3rd_task, execution_date=20231107T012011, start_date=20231107T012019, end_date=20231107T012051
[2023-11-07T01:20:51.704+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 275 for task 3rd_task (Bash command failed. The command returned a non-zero exit code 1.; 8877)
[2023-11-07T01:20:51.765+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-07T01:20:51.838+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
