[2023-11-09T02:05:15.923+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v03/run_id=scheduled__2023-11-05T00:00:00+00:00/task_id=3rd_task permission to 509
[2023-11-09T02:05:15.992+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v03/run_id=scheduled__2023-11-05T00:00:00+00:00/task_id=3rd_task permission to 509
[2023-11-09T02:05:16.064+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_google_data_v03.3rd_task scheduled__2023-11-05T00:00:00+00:00 [queued]>
[2023-11-09T02:05:16.083+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_google_data_v03.3rd_task scheduled__2023-11-05T00:00:00+00:00 [queued]>
[2023-11-09T02:05:16.085+0000] {taskinstance.py:1361} INFO - Starting attempt 5 of 6
[2023-11-09T02:05:16.126+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): 3rd_task> on 2023-11-05 00:00:00+00:00
[2023-11-09T02:05:16.138+0000] {standard_task_runner.py:57} INFO - Started process 2880 to run task
[2023-11-09T02:05:16.143+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fetch_google_data_v03', '3rd_task', 'scheduled__2023-11-05T00:00:00+00:00', '--job-id', '455', '--raw', '--subdir', 'DAGS_FOLDER/fetch_data.py', '--cfg-path', '/tmp/tmp64023b6o']
[2023-11-09T02:05:16.148+0000] {standard_task_runner.py:85} INFO - Job 455: Subtask 3rd_task
[2023-11-09T02:05:19.367+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v03/run_id=scheduled__2023-11-05T00:00:00+00:00/task_id=3rd_task permission to 509
[2023-11-09T02:05:19.383+0000] {task_command.py:416} INFO - Running <TaskInstance: fetch_google_data_v03.3rd_task scheduled__2023-11-05T00:00:00+00:00 [running]> on host a4fee2fb2c17
[2023-11-09T02:05:22.042+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Toema' AIRFLOW_CTX_DAG_ID='fetch_google_data_v03' AIRFLOW_CTX_TASK_ID='3rd_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-05T00:00:00+00:00'
[2023-11-09T02:05:22.045+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-09T02:05:22.047+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/src/scripts/fetch_automatic_downloads.py']
[2023-11-09T02:05:22.066+0000] {subprocess.py:86} INFO - Output:
[2023-11-09T02:05:23.880+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-11-09T02:05:23.884+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/src/scripts/fetch_automatic_downloads.py", line 18, in <module>
[2023-11-09T02:05:23.887+0000] {subprocess.py:93} INFO -     import wget  # pip3 install python3-wget, not pip install wget
[2023-11-09T02:05:23.890+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'wget'
[2023-11-09T02:05:23.923+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-11-09T02:05:23.954+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-11-09T02:05:24.004+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_google_data_v03, task_id=3rd_task, execution_date=20231105T000000, start_date=20231109T020516, end_date=20231109T020523
[2023-11-09T02:05:24.058+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 455 for task 3rd_task (Bash command failed. The command returned a non-zero exit code 1.; 2880)
[2023-11-09T02:05:24.831+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-09T02:05:24.900+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
