[2023-11-07T01:01:57.693+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v03/run_id=scheduled__2023-11-05T00:00:00+00:00/task_id=3rd_task permission to 509
[2023-11-07T01:01:57.775+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v03/run_id=scheduled__2023-11-05T00:00:00+00:00/task_id=3rd_task permission to 509
[2023-11-07T01:01:57.919+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_google_data_v03.3rd_task scheduled__2023-11-05T00:00:00+00:00 [queued]>
[2023-11-07T01:01:57.945+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_google_data_v03.3rd_task scheduled__2023-11-05T00:00:00+00:00 [queued]>
[2023-11-07T01:01:57.948+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 6
[2023-11-07T01:01:57.987+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): 3rd_task> on 2023-11-05 00:00:00+00:00
[2023-11-07T01:01:57.996+0000] {standard_task_runner.py:57} INFO - Started process 2343 to run task
[2023-11-07T01:01:58.004+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fetch_google_data_v03', '3rd_task', 'scheduled__2023-11-05T00:00:00+00:00', '--job-id', '258', '--raw', '--subdir', 'DAGS_FOLDER/fetch_data.py', '--cfg-path', '/tmp/tmpwjafnxx_']
[2023-11-07T01:01:58.009+0000] {standard_task_runner.py:85} INFO - Job 258: Subtask 3rd_task
[2023-11-07T01:01:58.207+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v03/run_id=scheduled__2023-11-05T00:00:00+00:00/task_id=3rd_task permission to 509
[2023-11-07T01:01:58.222+0000] {task_command.py:416} INFO - Running <TaskInstance: fetch_google_data_v03.3rd_task scheduled__2023-11-05T00:00:00+00:00 [running]> on host c4630ce72677
[2023-11-07T01:01:58.393+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Toema' AIRFLOW_CTX_DAG_ID='fetch_google_data_v03' AIRFLOW_CTX_TASK_ID='3rd_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-05T00:00:00+00:00'
[2023-11-07T01:01:58.396+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-07T01:01:58.399+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/src/scripts/fetch_automatic_downloads.py']
[2023-11-07T01:01:58.423+0000] {subprocess.py:86} INFO - Output:
[2023-11-07T01:01:58.955+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-11-07T01:01:58.956+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/src/scripts/fetch_automatic_downloads.py", line 18, in <module>
[2023-11-07T01:01:58.958+0000] {subprocess.py:93} INFO -     import wget  # pip3 install python3-wget, not pip install wget
[2023-11-07T01:01:58.960+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'wget'
[2023-11-07T01:01:58.967+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-11-07T01:01:58.987+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-11-07T01:01:58.994+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_google_data_v03, task_id=3rd_task, execution_date=20231105T000000, start_date=20231107T010157, end_date=20231107T010158
[2023-11-07T01:01:59.039+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 258 for task 3rd_task (Bash command failed. The command returned a non-zero exit code 1.; 2343)
[2023-11-07T01:01:59.063+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-07T01:01:59.097+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
