[2023-11-07T01:18:03.877+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=export_google_data_v02/run_id=scheduled__2023-11-03T00:00:00+00:00/task_id=3rd_task permission to 509
[2023-11-07T01:18:04.029+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=export_google_data_v02/run_id=scheduled__2023-11-03T00:00:00+00:00/task_id=3rd_task permission to 509
[2023-11-07T01:18:04.201+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: export_google_data_v02.3rd_task scheduled__2023-11-03T00:00:00+00:00 [queued]>
[2023-11-07T01:18:04.266+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: export_google_data_v02.3rd_task scheduled__2023-11-03T00:00:00+00:00 [queued]>
[2023-11-07T01:18:04.273+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-11-07T01:18:04.409+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): 3rd_task> on 2023-11-03 00:00:00+00:00
[2023-11-07T01:18:04.445+0000] {standard_task_runner.py:57} INFO - Started process 8730 to run task
[2023-11-07T01:18:04.462+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'export_google_data_v02', '3rd_task', 'scheduled__2023-11-03T00:00:00+00:00', '--job-id', '269', '--raw', '--subdir', 'DAGS_FOLDER/export_data.py', '--cfg-path', '/tmp/tmp2llk8qgd']
[2023-11-07T01:18:04.474+0000] {standard_task_runner.py:85} INFO - Job 269: Subtask 3rd_task
[2023-11-07T01:18:04.793+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=export_google_data_v02/run_id=scheduled__2023-11-03T00:00:00+00:00/task_id=3rd_task permission to 509
[2023-11-07T01:18:04.819+0000] {task_command.py:416} INFO - Running <TaskInstance: export_google_data_v02.3rd_task scheduled__2023-11-03T00:00:00+00:00 [running]> on host c4630ce72677
[2023-11-07T01:18:05.606+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Toema' AIRFLOW_CTX_DAG_ID='export_google_data_v02' AIRFLOW_CTX_TASK_ID='3rd_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-03T00:00:00+00:00'
[2023-11-07T01:18:05.620+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-07T01:18:05.629+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/src/scripts/export_data.py']
[2023-11-07T01:18:05.661+0000] {subprocess.py:86} INFO - Output:
[2023-11-07T01:18:32.712+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-11-07T01:18:32.718+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/src/scripts/export_data.py", line 57, in <module>
[2023-11-07T01:18:32.724+0000] {subprocess.py:93} INFO -     doc_utils.write_sources(sources_all, path_utils.path_to('sources_md'))
[2023-11-07T01:18:32.729+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/src/scripts/../../src/pipeline/doc_utils.py", line 106, in write_sources
[2023-11-07T01:18:32.732+0000] {subprocess.py:93} INFO -     with open(source_path, 'w', encoding="UTF-8", errors="ignore") as out:
[2023-11-07T01:18:32.735+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/opt/***/dags/docs/sources.md'
[2023-11-07T01:18:33.461+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-11-07T01:18:33.523+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-11-07T01:18:33.583+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=export_google_data_v02, task_id=3rd_task, execution_date=20231103T000000, start_date=20231107T011804, end_date=20231107T011833
[2023-11-07T01:18:33.703+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 269 for task 3rd_task (Bash command failed. The command returned a non-zero exit code 1.; 8730)
[2023-11-07T01:18:33.774+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-07T01:18:34.054+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
