[2023-11-07T03:28:15.555+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=check_S3_minio_bucket_v01/run_id=manual__2023-11-07T02:56:43.169605+00:00/task_id=12st_task permission to 509
[2023-11-07T03:28:15.625+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=check_S3_minio_bucket_v01/run_id=manual__2023-11-07T02:56:43.169605+00:00/task_id=12st_task permission to 509
[2023-11-07T03:28:15.696+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: check_S3_minio_bucket_v01.12st_task manual__2023-11-07T02:56:43.169605+00:00 [queued]>
[2023-11-07T03:28:15.720+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: check_S3_minio_bucket_v01.12st_task manual__2023-11-07T02:56:43.169605+00:00 [queued]>
[2023-11-07T03:28:15.722+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 6
[2023-11-07T03:28:15.769+0000] {taskinstance.py:1382} INFO - Executing <Task(S3KeySensor): 12st_task> on 2023-11-07 02:56:43.169605+00:00
[2023-11-07T03:28:15.788+0000] {standard_task_runner.py:57} INFO - Started process 31120 to run task
[2023-11-07T03:28:15.793+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'check_S3_minio_bucket_v01', '12st_task', 'manual__2023-11-07T02:56:43.169605+00:00', '--job-id', '343', '--raw', '--subdir', 'DAGS_FOLDER/check_S3_bucket.py', '--cfg-path', '/tmp/tmp0lmh6oxk']
[2023-11-07T03:28:15.800+0000] {standard_task_runner.py:85} INFO - Job 343: Subtask 12st_task
[2023-11-07T03:28:15.891+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=check_S3_minio_bucket_v01/run_id=manual__2023-11-07T02:56:43.169605+00:00/task_id=12st_task permission to 509
[2023-11-07T03:28:15.904+0000] {task_command.py:416} INFO - Running <TaskInstance: check_S3_minio_bucket_v01.12st_task manual__2023-11-07T02:56:43.169605+00:00 [running]> on host c4630ce72677
[2023-11-07T03:28:16.092+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Toema' AIRFLOW_CTX_DAG_ID='check_S3_minio_bucket_v01' AIRFLOW_CTX_TASK_ID='12st_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-07T02:56:43.169605+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-07T02:56:43.169605+00:00'
[2023-11-07T03:28:16.096+0000] {s3.py:106} INFO - Poking for key : s3://minio/c19/country_wise_latest.csv
[2023-11-07T03:28:16.123+0000] {base.py:73} INFO - Using connection ID 's3_minio_conn' for task execution.
[2023-11-07T03:28:16.126+0000] {connection_wrapper.py:343} INFO - AWS Connection (conn_id='s3_minio_conn', conn_type='aws') credentials retrieved from extra.
[2023-11-07T03:28:17.136+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 144, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 257, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 239, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 137, in poke
    return self._check_key(self.bucket_key)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 125, in _check_key
    obj = self.hook.head_object(key, bucket_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 136, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 90, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 879, in head_object
    return self.get_conn().head_object(Bucket=bucket_name, Key=key)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 928, in _make_api_call
    api_params = self._emit_api_params(
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 1043, in _emit_api_params
    self.meta.events.emit(
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/handlers.py", line 284, in validate_bucket_name
    raise ParamValidationError(report=error_msg)
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid bucket name "minio/c19": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
[2023-11-07T03:28:17.151+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=check_S3_minio_bucket_v01, task_id=12st_task, execution_date=20231107T025643, start_date=20231107T032815, end_date=20231107T032817
[2023-11-07T03:28:17.183+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 343 for task 12st_task (Parameter validation failed:
Invalid bucket name "minio/c19": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"; 31120)
[2023-11-07T03:28:17.215+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-07T03:28:17.243+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
