[2023-11-05T01:20:25.158+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v01/run_id=scheduled__2023-11-04T00:00:00+00:00/task_id=3rd_task permission to 509
[2023-11-05T01:20:25.195+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v01/run_id=scheduled__2023-11-04T00:00:00+00:00/task_id=3rd_task permission to 509
[2023-11-05T01:20:25.338+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_google_data_v01.3rd_task scheduled__2023-11-04T00:00:00+00:00 [queued]>
[2023-11-05T01:20:25.364+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_google_data_v01.3rd_task scheduled__2023-11-04T00:00:00+00:00 [queued]>
[2023-11-05T01:20:25.366+0000] {taskinstance.py:1361} INFO - Starting attempt 6 of 6
[2023-11-05T01:20:25.396+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): 3rd_task> on 2023-11-04 00:00:00+00:00
[2023-11-05T01:20:25.401+0000] {standard_task_runner.py:57} INFO - Started process 11340 to run task
[2023-11-05T01:20:25.406+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fetch_google_data_v01', '3rd_task', 'scheduled__2023-11-04T00:00:00+00:00', '--job-id', '164', '--raw', '--subdir', 'DAGS_FOLDER/fetch_data.py', '--cfg-path', '/tmp/tmpbhjkv22v']
[2023-11-05T01:20:25.408+0000] {standard_task_runner.py:85} INFO - Job 164: Subtask 3rd_task
[2023-11-05T01:20:25.491+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v01/run_id=scheduled__2023-11-04T00:00:00+00:00/task_id=3rd_task permission to 509
[2023-11-05T01:20:25.500+0000] {task_command.py:416} INFO - Running <TaskInstance: fetch_google_data_v01.3rd_task scheduled__2023-11-04T00:00:00+00:00 [running]> on host 264d7b91d87b
[2023-11-05T01:20:25.686+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Toema' AIRFLOW_CTX_DAG_ID='fetch_google_data_v01' AIRFLOW_CTX_TASK_ID='3rd_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-04T00:00:00+00:00'
[2023-11-05T01:20:25.689+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-05T01:20:25.693+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/src/scripts/fetch_automatic_downloads.py']
[2023-11-05T01:20:25.709+0000] {subprocess.py:86} INFO - Output:
[2023-11-05T01:20:26.192+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-11-05T01:20:26.194+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/src/scripts/fetch_automatic_downloads.py", line 18, in <module>
[2023-11-05T01:20:26.195+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
[2023-11-05T01:20:26.197+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
[2023-11-05T01:20:26.198+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 914, in _find_spec
[2023-11-05T01:20:26.199+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap_external>", line 1407, in find_spec
[2023-11-05T01:20:26.201+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap_external>", line 1379, in _get_spec
[2023-11-05T01:20:26.203+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap_external>", line 1510, in find_spec
[2023-11-05T01:20:26.205+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap_external>", line 1553, in _fill_cache
[2023-11-05T01:20:26.206+0000] {subprocess.py:93} INFO - OSError: [Errno 5] Input/output error: '/opt/***/dags/src/scripts'
[2023-11-05T01:20:26.215+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-11-05T01:20:26.235+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-11-05T01:20:26.261+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=fetch_google_data_v01, task_id=3rd_task, execution_date=20231104T000000, start_date=20231105T012025, end_date=20231105T012026
[2023-11-05T01:20:26.313+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 164 for task 3rd_task (Bash command failed. The command returned a non-zero exit code 1.; 11340)
[2023-11-05T01:20:26.345+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-05T01:20:26.378+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
