[2023-11-05T19:22:31.659+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v01/run_id=manual__2023-11-05T17:33:20.977072+00:00/task_id=3rd_task permission to 509
[2023-11-05T19:22:31.719+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v01/run_id=manual__2023-11-05T17:33:20.977072+00:00/task_id=3rd_task permission to 509
[2023-11-05T19:22:31.902+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_google_data_v01.3rd_task manual__2023-11-05T17:33:20.977072+00:00 [queued]>
[2023-11-05T19:22:31.930+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_google_data_v01.3rd_task manual__2023-11-05T17:33:20.977072+00:00 [queued]>
[2023-11-05T19:22:31.932+0000] {taskinstance.py:1361} INFO - Starting attempt 6 of 6
[2023-11-05T19:22:31.967+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): 3rd_task> on 2023-11-05 17:33:20.977072+00:00
[2023-11-05T19:22:31.977+0000] {standard_task_runner.py:57} INFO - Started process 9589 to run task
[2023-11-05T19:22:31.981+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fetch_google_data_v01', '3rd_task', 'manual__2023-11-05T17:33:20.977072+00:00', '--job-id', '188', '--raw', '--subdir', 'DAGS_FOLDER/fetch_data.py', '--cfg-path', '/tmp/tmpyg0_zzt4']
[2023-11-05T19:22:31.986+0000] {standard_task_runner.py:85} INFO - Job 188: Subtask 3rd_task
[2023-11-05T19:22:32.059+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v01/run_id=manual__2023-11-05T17:33:20.977072+00:00/task_id=3rd_task permission to 509
[2023-11-05T19:22:32.066+0000] {task_command.py:416} INFO - Running <TaskInstance: fetch_google_data_v01.3rd_task manual__2023-11-05T17:33:20.977072+00:00 [running]> on host 2e5f9e164ff4
[2023-11-05T19:22:32.205+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Toema' AIRFLOW_CTX_DAG_ID='fetch_google_data_v01' AIRFLOW_CTX_TASK_ID='3rd_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-05T17:33:20.977072+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-05T17:33:20.977072+00:00'
[2023-11-05T19:22:32.209+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-05T19:22:32.211+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/src/scripts/fetch_automatic_downloads.py']
[2023-11-05T19:22:32.226+0000] {subprocess.py:86} INFO - Output:
[2023-11-05T19:22:32.542+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-11-05T19:22:32.544+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/src/scripts/fetch_automatic_downloads.py", line 18, in <module>
[2023-11-05T19:22:32.545+0000] {subprocess.py:93} INFO -     import wget  # pip3 install python3-wget, not pip install wget
[2023-11-05T19:22:32.546+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'wget'
[2023-11-05T19:22:32.555+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-11-05T19:22:32.572+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-11-05T19:22:32.581+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=fetch_google_data_v01, task_id=3rd_task, execution_date=20231105T173320, start_date=20231105T192231, end_date=20231105T192232
[2023-11-05T19:22:32.606+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 188 for task 3rd_task (Bash command failed. The command returned a non-zero exit code 1.; 9589)
[2023-11-05T19:22:33.173+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-05T19:22:33.213+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
