[2023-11-05T22:16:01.945+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v03/run_id=scheduled__2023-11-04T00:00:00+00:00/task_id=3rd_task permission to 509
[2023-11-05T22:16:01.996+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v03/run_id=scheduled__2023-11-04T00:00:00+00:00/task_id=3rd_task permission to 509
[2023-11-05T22:16:02.057+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_google_data_v03.3rd_task scheduled__2023-11-04T00:00:00+00:00 [queued]>
[2023-11-05T22:16:02.076+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_google_data_v03.3rd_task scheduled__2023-11-04T00:00:00+00:00 [queued]>
[2023-11-05T22:16:02.077+0000] {taskinstance.py:1361} INFO - Starting attempt 6 of 6
[2023-11-05T22:16:02.104+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): 3rd_task> on 2023-11-04 00:00:00+00:00
[2023-11-05T22:16:02.115+0000] {standard_task_runner.py:57} INFO - Started process 48708 to run task
[2023-11-05T22:16:02.118+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fetch_google_data_v03', '3rd_task', 'scheduled__2023-11-04T00:00:00+00:00', '--job-id', '243', '--raw', '--subdir', 'DAGS_FOLDER/fetch_data.py', '--cfg-path', '/tmp/tmpnwj5vzp_']
[2023-11-05T22:16:02.121+0000] {standard_task_runner.py:85} INFO - Job 243: Subtask 3rd_task
[2023-11-05T22:16:02.185+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v03/run_id=scheduled__2023-11-04T00:00:00+00:00/task_id=3rd_task permission to 509
[2023-11-05T22:16:02.193+0000] {task_command.py:416} INFO - Running <TaskInstance: fetch_google_data_v03.3rd_task scheduled__2023-11-04T00:00:00+00:00 [running]> on host 2e5f9e164ff4
[2023-11-05T22:16:02.316+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Toema' AIRFLOW_CTX_DAG_ID='fetch_google_data_v03' AIRFLOW_CTX_TASK_ID='3rd_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-04T00:00:00+00:00'
[2023-11-05T22:16:02.318+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-05T22:16:02.321+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/src/scripts/fetch_automatic_downloads.py']
[2023-11-05T22:16:02.338+0000] {subprocess.py:86} INFO - Output:
[2023-11-05T22:16:02.893+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-11-05T22:16:02.894+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/src/scripts/fetch_automatic_downloads.py", line 18, in <module>
[2023-11-05T22:16:02.895+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/wget.py", line 28, in <module>
[2023-11-05T22:16:02.896+0000] {subprocess.py:93} INFO -     import urllib.request as ulib
[2023-11-05T22:16:02.897+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/urllib/request.py", line 87, in <module>
[2023-11-05T22:16:02.898+0000] {subprocess.py:93} INFO -     import hashlib
[2023-11-05T22:16:02.899+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
[2023-11-05T22:16:02.900+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
[2023-11-05T22:16:02.901+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 914, in _find_spec
[2023-11-05T22:16:02.902+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap_external>", line 1407, in find_spec
[2023-11-05T22:16:02.903+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap_external>", line 1379, in _get_spec
[2023-11-05T22:16:02.904+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap_external>", line 1510, in find_spec
[2023-11-05T22:16:02.904+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap_external>", line 1553, in _fill_cache
[2023-11-05T22:16:02.905+0000] {subprocess.py:93} INFO - OSError: [Errno 5] Input/output error: '/opt/***/dags/src/scripts'
[2023-11-05T22:16:02.906+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-11-05T22:16:02.920+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-11-05T22:16:02.933+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=fetch_google_data_v03, task_id=3rd_task, execution_date=20231104T000000, start_date=20231105T221602, end_date=20231105T221602
[2023-11-05T22:16:02.954+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 243 for task 3rd_task (Bash command failed. The command returned a non-zero exit code 1.; 48708)
[2023-11-05T22:16:03.688+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-05T22:16:03.722+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
