[2023-11-05T22:05:55.322+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v03/run_id=scheduled__2023-11-04T00:00:00+00:00/task_id=3rd_task permission to 509
[2023-11-05T22:05:55.372+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v03/run_id=scheduled__2023-11-04T00:00:00+00:00/task_id=3rd_task permission to 509
[2023-11-05T22:05:55.425+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_google_data_v03.3rd_task scheduled__2023-11-04T00:00:00+00:00 [queued]>
[2023-11-05T22:05:55.438+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_google_data_v03.3rd_task scheduled__2023-11-04T00:00:00+00:00 [queued]>
[2023-11-05T22:05:55.440+0000] {taskinstance.py:1361} INFO - Starting attempt 5 of 6
[2023-11-05T22:05:55.459+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): 3rd_task> on 2023-11-04 00:00:00+00:00
[2023-11-05T22:05:55.465+0000] {standard_task_runner.py:57} INFO - Started process 46132 to run task
[2023-11-05T22:05:55.468+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fetch_google_data_v03', '3rd_task', 'scheduled__2023-11-04T00:00:00+00:00', '--job-id', '239', '--raw', '--subdir', 'DAGS_FOLDER/fetch_data.py', '--cfg-path', '/tmp/tmp6meu_d7a']
[2023-11-05T22:05:55.471+0000] {standard_task_runner.py:85} INFO - Job 239: Subtask 3rd_task
[2023-11-05T22:05:55.527+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v03/run_id=scheduled__2023-11-04T00:00:00+00:00/task_id=3rd_task permission to 509
[2023-11-05T22:05:55.534+0000] {task_command.py:416} INFO - Running <TaskInstance: fetch_google_data_v03.3rd_task scheduled__2023-11-04T00:00:00+00:00 [running]> on host 2e5f9e164ff4
[2023-11-05T22:05:55.633+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Toema' AIRFLOW_CTX_DAG_ID='fetch_google_data_v03' AIRFLOW_CTX_TASK_ID='3rd_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-04T00:00:00+00:00'
[2023-11-05T22:05:55.635+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-05T22:05:55.638+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/src/scripts/fetch_automatic_downloads.py']
[2023-11-05T22:05:55.649+0000] {subprocess.py:86} INFO - Output:
[2023-11-05T22:05:57.008+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-11-05T22:05:57.009+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/src/scripts/fetch_automatic_downloads.py", line 42, in <module>
[2023-11-05T22:05:57.010+0000] {subprocess.py:93} INFO -     automatic_downloads = config.read_config(cc_by=True, cc_by_sa=True, google_tos=True, cc_by_nc=True,
[2023-11-05T22:05:57.012+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/src/scripts/../../src/pipeline/config.py", line 70, in read_config
[2023-11-05T22:05:57.013+0000] {subprocess.py:93} INFO -     allowlist = read_allowlist()
[2023-11-05T22:05:57.014+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/src/scripts/../../src/pipeline/config.py", line 38, in read_allowlist
[2023-11-05T22:05:57.015+0000] {subprocess.py:93} INFO -     with open(ALLOWLIST_YAML, encoding="UTF-8", errors="ignore") as file:
[2023-11-05T22:05:57.016+0000] {subprocess.py:93} INFO - OSError: [Errno 5] Input/output error: '/opt/***/dags/src/config/allowlist.yaml'
[2023-11-05T22:05:57.047+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-11-05T22:05:57.064+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-11-05T22:05:57.085+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_google_data_v03, task_id=3rd_task, execution_date=20231104T000000, start_date=20231105T220555, end_date=20231105T220557
[2023-11-05T22:05:57.122+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 239 for task 3rd_task (Bash command failed. The command returned a non-zero exit code 1.; 46132)
[2023-11-05T22:05:58.197+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-05T22:05:58.285+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
