[2023-11-05T20:41:52.502+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v03/run_id=manual__2023-11-05T20:30:45.446182+00:00/task_id=3rd_task permission to 509
[2023-11-05T20:41:52.542+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v03/run_id=manual__2023-11-05T20:30:45.446182+00:00/task_id=3rd_task permission to 509
[2023-11-05T20:41:52.599+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_google_data_v03.3rd_task manual__2023-11-05T20:30:45.446182+00:00 [queued]>
[2023-11-05T20:41:52.618+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_google_data_v03.3rd_task manual__2023-11-05T20:30:45.446182+00:00 [queued]>
[2023-11-05T20:41:52.619+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 6
[2023-11-05T20:41:52.639+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): 3rd_task> on 2023-11-05 20:30:45.446182+00:00
[2023-11-05T20:41:52.645+0000] {standard_task_runner.py:57} INFO - Started process 35306 to run task
[2023-11-05T20:41:52.649+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fetch_google_data_v03', '3rd_task', 'manual__2023-11-05T20:30:45.446182+00:00', '--job-id', '206', '--raw', '--subdir', 'DAGS_FOLDER/fetch_data.py', '--cfg-path', '/tmp/tmpzdjq7yf3']
[2023-11-05T20:41:52.655+0000] {standard_task_runner.py:85} INFO - Job 206: Subtask 3rd_task
[2023-11-05T20:41:52.719+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v03/run_id=manual__2023-11-05T20:30:45.446182+00:00/task_id=3rd_task permission to 509
[2023-11-05T20:41:52.726+0000] {task_command.py:416} INFO - Running <TaskInstance: fetch_google_data_v03.3rd_task manual__2023-11-05T20:30:45.446182+00:00 [running]> on host 2e5f9e164ff4
[2023-11-05T20:41:52.821+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Toema' AIRFLOW_CTX_DAG_ID='fetch_google_data_v03' AIRFLOW_CTX_TASK_ID='3rd_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-05T20:30:45.446182+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-05T20:30:45.446182+00:00'
[2023-11-05T20:41:52.824+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-05T20:41:52.827+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/src/scripts/fetch_automatic_downloads.py']
[2023-11-05T20:41:52.841+0000] {subprocess.py:86} INFO - Output:
[2023-11-05T20:41:53.007+0000] {subprocess.py:93} INFO - python: can't open file '/opt/***/dags/src/scripts/fetch_automatic_downloads.py': [Errno 5] Input/output error
[2023-11-05T20:41:53.014+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-11-05T20:41:53.032+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-11-05T20:41:53.037+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_google_data_v03, task_id=3rd_task, execution_date=20231105T203045, start_date=20231105T204152, end_date=20231105T204153
[2023-11-05T20:41:53.058+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 206 for task 3rd_task (Bash command failed. The command returned a non-zero exit code 2.; 35306)
[2023-11-05T20:41:53.380+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-05T20:41:53.419+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
