[2023-11-05T21:22:07.522+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v03/run_id=manual__2023-11-05T20:30:45.446182+00:00/task_id=3rd_task permission to 509
[2023-11-05T21:22:07.588+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v03/run_id=manual__2023-11-05T20:30:45.446182+00:00/task_id=3rd_task permission to 509
[2023-11-05T21:22:07.693+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_google_data_v03.3rd_task manual__2023-11-05T20:30:45.446182+00:00 [queued]>
[2023-11-05T21:22:07.724+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_google_data_v03.3rd_task manual__2023-11-05T20:30:45.446182+00:00 [queued]>
[2023-11-05T21:22:07.726+0000] {taskinstance.py:1361} INFO - Starting attempt 6 of 6
[2023-11-05T21:22:07.752+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): 3rd_task> on 2023-11-05 20:30:45.446182+00:00
[2023-11-05T21:22:07.763+0000] {standard_task_runner.py:57} INFO - Started process 39816 to run task
[2023-11-05T21:22:07.767+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fetch_google_data_v03', '3rd_task', 'manual__2023-11-05T20:30:45.446182+00:00', '--job-id', '213', '--raw', '--subdir', 'DAGS_FOLDER/fetch_data.py', '--cfg-path', '/tmp/tmpjvgmg0am']
[2023-11-05T21:22:07.772+0000] {standard_task_runner.py:85} INFO - Job 213: Subtask 3rd_task
[2023-11-05T21:22:07.882+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v03/run_id=manual__2023-11-05T20:30:45.446182+00:00/task_id=3rd_task permission to 509
[2023-11-05T21:22:07.893+0000] {task_command.py:416} INFO - Running <TaskInstance: fetch_google_data_v03.3rd_task manual__2023-11-05T20:30:45.446182+00:00 [running]> on host 2e5f9e164ff4
[2023-11-05T21:22:08.056+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Toema' AIRFLOW_CTX_DAG_ID='fetch_google_data_v03' AIRFLOW_CTX_TASK_ID='3rd_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-05T20:30:45.446182+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-05T20:30:45.446182+00:00'
[2023-11-05T21:22:08.058+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-05T21:22:08.064+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/src/scripts/fetch_automatic_downloads.py']
[2023-11-05T21:22:08.082+0000] {subprocess.py:86} INFO - Output:
[2023-11-05T21:22:08.434+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-11-05T21:22:08.436+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/src/scripts/fetch_automatic_downloads.py", line 15, in <module>
[2023-11-05T21:22:08.438+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/logging/__init__.py", line 26, in <module>
[2023-11-05T21:22:08.439+0000] {subprocess.py:93} INFO -     import sys, os, time, io, re, traceback, warnings, weakref, collections.abc
[2023-11-05T21:22:08.441+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/traceback.py", line 5, in <module>
[2023-11-05T21:22:08.442+0000] {subprocess.py:93} INFO -     import linecache
[2023-11-05T21:22:08.443+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
[2023-11-05T21:22:08.445+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
[2023-11-05T21:22:08.446+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 914, in _find_spec
[2023-11-05T21:22:08.447+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap_external>", line 1407, in find_spec
[2023-11-05T21:22:08.449+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap_external>", line 1379, in _get_spec
[2023-11-05T21:22:08.450+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap_external>", line 1510, in find_spec
[2023-11-05T21:22:08.451+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap_external>", line 1553, in _fill_cache
[2023-11-05T21:22:08.453+0000] {subprocess.py:93} INFO - OSError: [Errno 5] Input/output error: '/opt/***/dags/src/scripts'
[2023-11-05T21:22:08.454+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-11-05T21:22:08.476+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-11-05T21:22:08.486+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=fetch_google_data_v03, task_id=3rd_task, execution_date=20231105T203045, start_date=20231105T212207, end_date=20231105T212208
[2023-11-05T21:22:08.513+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 213 for task 3rd_task (Bash command failed. The command returned a non-zero exit code 1.; 39816)
[2023-11-05T21:22:09.323+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-05T21:22:09.360+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
