[2023-11-07T00:47:40.833+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v03/run_id=scheduled__2023-11-06T00:00:00+00:00/task_id=3rd_task permission to 509
[2023-11-07T00:47:40.959+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v03/run_id=scheduled__2023-11-06T00:00:00+00:00/task_id=3rd_task permission to 509
[2023-11-07T00:47:41.209+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_google_data_v03.3rd_task scheduled__2023-11-06T00:00:00+00:00 [queued]>
[2023-11-07T00:47:41.275+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_google_data_v03.3rd_task scheduled__2023-11-06T00:00:00+00:00 [queued]>
[2023-11-07T00:47:41.278+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-11-07T00:47:41.369+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): 3rd_task> on 2023-11-06 00:00:00+00:00
[2023-11-07T00:47:41.408+0000] {standard_task_runner.py:57} INFO - Started process 214 to run task
[2023-11-07T00:47:41.440+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fetch_google_data_v03', '3rd_task', 'scheduled__2023-11-06T00:00:00+00:00', '--job-id', '255', '--raw', '--subdir', 'DAGS_FOLDER/fetch_data.py', '--cfg-path', '/tmp/tmp9q4duaia']
[2023-11-07T00:47:41.471+0000] {standard_task_runner.py:85} INFO - Job 255: Subtask 3rd_task
[2023-11-07T00:47:41.812+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v03/run_id=scheduled__2023-11-06T00:00:00+00:00/task_id=3rd_task permission to 509
[2023-11-07T00:47:41.833+0000] {task_command.py:416} INFO - Running <TaskInstance: fetch_google_data_v03.3rd_task scheduled__2023-11-06T00:00:00+00:00 [running]> on host 2e5f9e164ff4
[2023-11-07T00:47:43.820+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Toema' AIRFLOW_CTX_DAG_ID='fetch_google_data_v03' AIRFLOW_CTX_TASK_ID='3rd_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-06T00:00:00+00:00'
[2023-11-07T00:47:43.829+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-07T00:47:43.835+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/src/scripts/fetch_automatic_downloads.py']
[2023-11-07T00:47:43.900+0000] {subprocess.py:86} INFO - Output:
[2023-11-07T00:51:53.738+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
[2023-11-07T00:51:54.425+0000] {process_utils.py:131} INFO - Sending 15 to group 214. PIDs of all processes in the group: [215, 214]
[2023-11-07T00:51:54.446+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 214
[2023-11-07T00:51:54.678+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-11-07T00:51:54.931+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2023-11-07T00:51:56.188+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 201, in execute
    result = self.subprocess_hook.run_command(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1634, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-11-07T00:51:56.366+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_google_data_v03, task_id=3rd_task, execution_date=20231106T000000, start_date=20231107T004741, end_date=20231107T005156
[2023-11-07T00:51:56.830+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 255 for task 3rd_task (Task received SIGTERM signal; 214)
[2023-11-07T00:51:56.909+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=215, status='terminated', started='00:47:43') (215) terminated with exit code None
[2023-11-07T00:51:56.920+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=214, status='terminated', exitcode=1, started='00:47:40') (214) terminated with exit code 1
[2023-11-07T00:51:56.938+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 143
[2023-11-07T00:51:57.502+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
