[2023-11-05T00:04:09.899+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v01/run_id=manual__2023-11-04T23:44:02.004706+00:00/task_id=3rd_task permission to 509
[2023-11-05T00:04:09.965+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v01/run_id=manual__2023-11-04T23:44:02.004706+00:00/task_id=3rd_task permission to 509
[2023-11-05T00:04:10.054+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_google_data_v01.3rd_task manual__2023-11-04T23:44:02.004706+00:00 [queued]>
[2023-11-05T00:04:10.079+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_google_data_v01.3rd_task manual__2023-11-04T23:44:02.004706+00:00 [queued]>
[2023-11-05T00:04:10.081+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 6
[2023-11-05T00:04:10.118+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): 3rd_task> on 2023-11-04 23:44:02.004706+00:00
[2023-11-05T00:04:10.130+0000] {standard_task_runner.py:57} INFO - Started process 2635 to run task
[2023-11-05T00:04:10.135+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fetch_google_data_v01', '3rd_task', 'manual__2023-11-04T23:44:02.004706+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/fetch_data.py', '--cfg-path', '/tmp/tmprsr1vmi6']
[2023-11-05T00:04:10.140+0000] {standard_task_runner.py:85} INFO - Job 133: Subtask 3rd_task
[2023-11-05T00:04:10.251+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v01/run_id=manual__2023-11-04T23:44:02.004706+00:00/task_id=3rd_task permission to 509
[2023-11-05T00:04:10.258+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 133 for task 3rd_task ([Errno 5] Input/output error: '/opt/airflow/logs/dag_id=fetch_google_data_v01/run_id=manual__2023-11-04T23:44:02.004706+00:00/task_id=3rd_task/attempt=3.log'; 2635)
[2023-11-05T00:04:10.311+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-05T00:04:10.350+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
