[2023-11-05T00:28:15.204+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v02/run_id=manual__2023-11-04T23:57:57.757578+00:00/task_id=2nd_task2 permission to 509
[2023-11-05T00:28:15.266+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v02/run_id=manual__2023-11-04T23:57:57.757578+00:00/task_id=2nd_task2 permission to 509
[2023-11-05T00:28:15.344+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_google_data_v02.2nd_task2 manual__2023-11-04T23:57:57.757578+00:00 [queued]>
[2023-11-05T00:28:15.363+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_google_data_v02.2nd_task2 manual__2023-11-04T23:57:57.757578+00:00 [queued]>
[2023-11-05T00:28:15.365+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 6
[2023-11-05T00:28:15.391+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): 2nd_task2> on 2023-11-04 23:57:57.757578+00:00
[2023-11-05T00:28:15.401+0000] {standard_task_runner.py:57} INFO - Started process 5257 to run task
[2023-11-05T00:28:15.407+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fetch_google_data_v02', '2nd_task2', 'manual__2023-11-04T23:57:57.757578+00:00', '--job-id', '150', '--raw', '--subdir', 'DAGS_FOLDER/fetch_data2.py', '--cfg-path', '/tmp/tmphpwf1qyd']
[2023-11-05T00:28:15.411+0000] {standard_task_runner.py:85} INFO - Job 150: Subtask 2nd_task2
[2023-11-05T00:28:15.500+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v02/run_id=manual__2023-11-04T23:57:57.757578+00:00/task_id=2nd_task2 permission to 509
[2023-11-05T00:28:15.509+0000] {task_command.py:416} INFO - Running <TaskInstance: fetch_google_data_v02.2nd_task2 manual__2023-11-04T23:57:57.757578+00:00 [running]> on host 264d7b91d87b
[2023-11-05T00:28:15.639+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Toema' AIRFLOW_CTX_DAG_ID='fetch_google_data_v02' AIRFLOW_CTX_TASK_ID='2nd_task2' AIRFLOW_CTX_EXECUTION_DATE='2023-11-04T23:57:57.757578+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-04T23:57:57.757578+00:00'
[2023-11-05T00:28:15.641+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-05T00:28:15.644+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/dags/pathToOpenCovid19.lnk']
[2023-11-05T00:28:15.662+0000] {subprocess.py:86} INFO - Output:
[2023-11-05T00:28:15.672+0000] {subprocess.py:93} INFO - /bin/bash: line 1: cd: /opt/***/dags/pathToOpenCovid19.lnk: Not a directory
[2023-11-05T00:28:15.674+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-11-05T00:28:15.695+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-11-05T00:28:15.702+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_google_data_v02, task_id=2nd_task2, execution_date=20231104T235757, start_date=20231105T002815, end_date=20231105T002815
[2023-11-05T00:28:15.727+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 150 for task 2nd_task2 (Bash command failed. The command returned a non-zero exit code 1.; 5257)
[2023-11-05T00:28:15.740+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-05T00:28:15.777+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
